# Generated by theme/render.sh from theme/templates/fish-theme.fish.
# Edit the template or theme/palette.sh, not this file.
# Globals (-g) override any universal colours left in fish_variables.
# Nothing informative is darker than gray6 on the gray0 background.

set -g fish_color_normal e3d6c9
set -g fish_color_command f4b585
set -g fish_color_keyword e28dc6
set -g fish_color_quote efbf71
set -g fish_color_redirection 7ec9a3
set -g fish_color_end ef934d
set -g fish_color_error f16e65
set -g fish_color_param d9cdb5
set -g fish_color_option abd4bf
set -g fish_color_valid_path --underline
set -g fish_color_comment 9a9c8b
set -g fish_color_operator 7ec9a3
set -g fish_color_escape ebadd6
set -g fish_color_autosuggestion 888e7b
set -g fish_color_selection f4decd --background=3b403c
set -g fish_color_search_match --background=3b403c
set -g fish_color_history_current --bold
set -g fish_color_cancel ef968f
set -g fish_color_cwd f4b585
set -g fish_color_cwd_root f16e65
set -g fish_color_user 7ec97e
set -g fish_color_host 71b4d6
set -g fish_color_host_remote efbf71
set -g fish_color_status f16e65

set -g fish_pager_color_prefix f4b585 --bold
set -g fish_pager_color_completion d9cdb5
set -g fish_pager_color_description 9a9c8b
set -g fish_pager_color_progress e3d6c9 --background=272a28
set -g fish_pager_color_selected_background --background=3b403c
set -g fish_pager_color_selected_prefix f4b585 --bold
set -g fish_pager_color_selected_completion f4decd
set -g fish_pager_color_selected_description d9cdb5
