# Generated by theme/render.sh from theme/templates/fish-theme.fish.
# Edit the template or theme/palette.sh, not this file.
# Globals (-g) override any universal colours left in fish_variables.
# Nothing informative is darker than gray6 on the gray0 background.

set -g fish_color_normal {{gray10:hex}}
set -g fish_color_command {{orange7:hex}}
set -g fish_color_keyword {{magenta7:hex}}
set -g fish_color_quote {{yellow:hex}}
set -g fish_color_redirection {{cyan6:hex}}
set -g fish_color_end {{orange6:hex}}
set -g fish_color_error {{red6:hex}}
set -g fish_color_param {{gray9:hex}}
set -g fish_color_option {{cyan7:hex}}
set -g fish_color_valid_path --underline
set -g fish_color_comment {{gray7:hex}}
set -g fish_color_operator {{cyan6:hex}}
set -g fish_color_escape {{magenta8:hex}}
set -g fish_color_autosuggestion {{gray6:hex}}
set -g fish_color_selection {{white:hex}} --background={{gray3:hex}}
set -g fish_color_search_match --background={{gray3:hex}}
set -g fish_color_history_current --bold
set -g fish_color_cancel {{red7:hex}}
set -g fish_color_cwd {{orange7:hex}}
set -g fish_color_cwd_root {{red6:hex}}
set -g fish_color_user {{green6:hex}}
set -g fish_color_host {{blue6:hex}}
set -g fish_color_host_remote {{yellow:hex}}
set -g fish_color_status {{red6:hex}}

set -g fish_pager_color_prefix {{orange7:hex}} --bold
set -g fish_pager_color_completion {{gray9:hex}}
set -g fish_pager_color_description {{gray7:hex}}
set -g fish_pager_color_progress {{gray10:hex}} --background={{gray2:hex}}
set -g fish_pager_color_selected_background --background={{gray3:hex}}
set -g fish_pager_color_selected_prefix {{orange7:hex}} --bold
set -g fish_pager_color_selected_completion {{white:hex}}
set -g fish_pager_color_selected_description {{gray9:hex}}
